### ISSUE TITLE
How to make it work for User Units?

### ISSUE THREAD

**Issue by erenoglu** [naraesk/plasma-systemd#2]
I can't get my user units to be recognized. There's no option to click if the mentioned unit is a user unit (systemctl --user start service_name).

**Comment by naraesk** [comment]
What do you mean by "no option to click"? The UI should look identical.

Currently, there is no option to add the user argument to the command. But if I find some time on the weekend I can add it.

**Comment by erenoglu** [comment]
Indeed, there's no UI for it. You just add a service name and click +
I guess by default it chooses the system unit which wont work for my user units.

If there was a click box to indicate if service is a user service, it would be good.

It would also be good if it could enumarate all services and let you choose by clicking boxes rather than writing the name one by one and risk a typo, or question yourself if you should add .service to the end or not (ie shall I write onedrive or onedrive.service)

**Comment by erenoglu** [comment]
and thanks a lot for your time for this widget and your quick response.

**Comment by naraesk** [comment]
Sorry for the delay. Please have a look at version 1.2.0, user units should now work.

Yes, a list of all available services would be good. Will come sooner or later. ;-)
