### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by peteyycz** [naraesk/plasma-systemd#8]
I've built it from source and added it to my taskbar and desktop. When I try to open it the dialog box is empty.

`journalctl -xe`:
```
jan 14 09:46:00 peteyycz-laptop plasmashell[20071]: trying to show an empty dialog
jan 14 09:46:02 peteyycz-laptop plasmashell[20071]: trying to show an empty dialog
jan 14 09:46:03 peteyycz-laptop plasmashell[20071]: trying to show an empty dialog
jan 14 09:46:06 peteyycz-laptop plasmashell[20071]: TODO: port listCategories()
jan 14 09:46:15 peteyycz-laptop plasmashell[20071]: Arrived mimeData () ("text/x-plasmoidservicename") at 771 ,  309
jan 14 09:46:15 peteyycz-laptop plasmashell[20071]: adding "org.kde.systemd-control"
jan 14 09:46:18 peteyycz-laptop plasmashell[20071]: trying to show an empty dialog
```

**Comment by naraesk** [comment]
What do you mean by dialog box? The widget itself is indeed empty after adding it to the desktop. You have to open the config dialog and customize it.

**Comment by peteyycz** [comment]
Ah I see! I think some info about this would be helpful instead of the empty window popup :D If you don't mind I could create a PR about it, how do you usually do you build -> debug loop? Do you always do a make changed to the codebase and then `make install` and add a new widget?

**Comment by naraesk** [comment]
> Ah I see! I think some info about this would be helpful instead of the empty window popup :D If you don't mind I could create a PR about it,

Yes, that would definetly make sense. Would appreciate any help. :-)

> how do you usually do you build -> debug loop? Do you always do a make changed to the codebase and then `make install` and add a new widget?

Yes
